### ISSUE TITLE
valamis liferay 6.2 mysql

### ISSUE THREAD

**Issue by prthy** [arcusys/valamis-lrs#6]
hi, i get portlet temporarily unavailable everytime i install it from marketplace . my database is Mysql.

Please help me solve this issue

**Comment by yglushonkova** [comment]
Hello! Can you please send error from Liferay log.

**Comment by prthy** [comment]
16:10:32,848 ERROR [http-bio-8080-exec-7][render_portlet_jsp:132] null
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal1.LEARN_SETTINGS' doesn't exist
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1375)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
        at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
        at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
        at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
        at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
        at scala.slick.jdbc.Invoker$class.firstOption(Invoker.scala:29)
        at scala.slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
        at com.arcusys.valamis.settings.SettingStorageImpl$$anonfun$getByKey$1.apply(SettingStorageImpl.scala:22)
        at com.arcusys.valamis.settings.SettingStorageImpl$$anonfun$getByKey$1.apply(SettingStorageImpl.scala:21)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
